#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# latest stable NGINX 1.4.x with websocket support
KERNEL_VERSION="$(uname -v)"
if [[ $KERNEL_VERSION == *Debian* ]] ;
then
	NGINX_INSTALLED="$(dpkg -s nginx-full ; echo $?)"
	if [ $NGINX_INSTALLED -eq 0 ] ;
	then
		NGINX=/usr/sbin/nginx
		NGINX_VERSION="$($NGINX -v 2>&1 | sed 's/nginx version: nginx\/\(.*\)/\1/')"
		echo $NGINX_VERSION
		IFS='.' read -a NGINX_VERSION <<< "$NGINX_VERSION"
		if [ ${NGINX_VERSION[0]} -ge 1 ] && [ ${NGINX_VERSION[1]} -ge 4 ]; then
			echo "Nginx already lastest version."
			exit 0
		else
			echo "Nginx-full is not up to date, I try to upgrade it..."
			apt-get install -t testing nginx-full
			if [ $? -ne 0 ]; then
				echo "Failed to install testing nginx (v1.4.4)."
				echo "Please add this to your sources : /etc/apt/source.list.d/testing.list"
				echo "Create the file and add this line :"
				echo "  deb http://ftp.us.debian.org/debian testing main"
				exit 1
			else
				exit 0
			fi
		fi
	else
		echo "Nginx-full is not installed, I try to install it..."
		apt-get install -t testing nginx-full
		if [ $? -ne 0 ]; then
			echo "Failed to install testing nginx (v1.4.4)."
			echo "Please add this to your sources : /etc/apt/source.list.d/testing.list"
			echo "Create the file and add this line :"
			echo "  deb http://ftp.us.debian.org/debian testing main"
			exit 1
		else
			exit 0
		fi
	fi
	apt-get install dnsutils
else
	add-apt-repository -y ppa:nginx/stable
	apt-get update
	apt-get install -y nginx dnsutils
fi

if ! grep -q dokku-nginx-reload "/etc/sudoers"; then
  touch /etc/sudoers.tmp
  cp /etc/sudoers /tmp/sudoers.new
  echo "%dokku ALL=(ALL)NOPASSWD:/etc/init.d/nginx reload # dokku-nginx-reload" >> /tmp/sudoers.new
  EDITOR="cp /tmp/sudoers.new" visudo
  rm /tmp/sudoers.new
fi

echo "include $DOKKU_ROOT/*/nginx.conf;" > /etc/nginx/conf.d/dokku.conf

sed -i 's/# server_names_hash_bucket_size/server_names_hash_bucket_size/' /etc/nginx/nginx.conf

if [[ ! -f  "$DOKKU_ROOT/VHOST" ]]; then
  [[ $(dig +short $(< "$DOKKU_ROOT/HOSTNAME")) ]] && cp "$DOKKU_ROOT/HOSTNAME" "$DOKKU_ROOT/VHOST"
fi

/etc/init.d/nginx start
